stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd apps/api
    - yarn install
    - yarn db:start
    - yarn db:migrate
    - yarn build
    - yarn start
deploy:
  stage: deploy
  script:
    - echo "Deploying to railway server"
    - scp -o StrictHostKeyChecking=no -o User=user -o Port=22 -r dist/* user@railway_server_ip:apps/api
  only:
    - master
  environment:
    name: railway
    url: http://railway_server_ip
  variables:
    GIT_STRATEGY: clone
    GIT_CLONE_EXTRA_FLAGS: "--depth=1"
    GIT_CLONE_ATTEMPTS: 3
    GITLAB_TOKEN: $CI_JOB_TOKEN
